name=MiniMicroKit-PTL
version=1.0.0
author=GelectronLAB
maintainer=GelectronLAB <gunaneg011@gmail.com>
sentence=Official library for MiniMicroKit PTL (ESP32-C3 Supermini) with OLED, LEDs, Buzzer, Encoder, and IoT support.
paragraph=A feature-rich library designed for classroom AI and IoT projects, supporting Teachable Machine Webapp via MQTT.
category=Device Control
url=https://github.com/GUNANAG38/MiniMicroKit-PTL
architectures=esp32
depends=Adafruit GFX Library, Adafruit SSD1306, PubSubClient, WiFi